import { createVuetify } from 'vuetify'
import { VNumberInput } from 'vuetify/labs/VNumberInput'
import {
  VAlert,
  VCard,
  VCardTitle,
  VCardText,
  VCardActions,
  VDialog,
  VBtn,
  VIcon,
  VOverlay,
  VSnackbar,
  VEmptyState,
  VImg,
  VExpansionPanels,
  VExpansionPanel,
  VExpansionPanelTitle,
  VExpansionPanelText,
  VRadioGroup,
  VRadio,
  VCheckbox,
  VTextField,
  VSelect,
  VSwitch,
  VBtnToggle,
  VContainer,
  VList,
  VListItem,
  VListItemTitle,
  VMain,
  VApp,
  VAppBar,
  VProgressCircular,
  VRow,
  VCol,
  VSpacer,
  VDivider,
  VTooltip,
  VNavigationDrawer,
  VCombobox,
} from 'vuetify/lib/components/index.mjs'
import 'vuetify/styles'
import { aliases, mdi } from 'vuetify/iconsets/mdi'

const vuetify = createVuetify({
  icons: {
    defaultSet: 'mdi', // Set MDI (Material Design Icons) as the default icon set
    aliases,
    sets: { mdi },
  },
  components: {
    VCard,
    VCardTitle,
    VCardText,
    VCardActions,
    VDialog,
    VBtn,
    VAlert,
    VIcon,
    VSnackbar,
    VEmptyState,
    VImg,
    VExpansionPanels,
    VExpansionPanel,
    VExpansionPanelTitle,
    VExpansionPanelText,
    VNumberInput,
    VRadioGroup,
    VRadio,
    VCheckbox,
    VTextField,
    VSelect,
    VSwitch,
    VBtnToggle,
    VContainer,
    VList,
    VListItem,
    VListItemTitle,
    VMain,
    VApp,
    VAppBar,
    VOverlay,
    VProgressCircular,
    VRow,
    VCol,
    VSpacer,
    VDivider,
    VTooltip,
    VNavigationDrawer,
    VCombobox,
  },
  defaults: {
    VCheckbox: {
      color: 'primary',
    },
    VRadioGroup: {
      color: 'primary',
    },
    VRadio: {
      color: 'primary',
    },
    VSwitch: {
      color: 'primary',
    },
  },
})
export default vuetify
